# Typus Models Configuration File
#
# Use the README file as a reference to customize settings.

Schedule:
  fields:
    default: effect_at
    form: effect_at
  order_by: 
  relationships: schedule_members
  search: 
  application: TokyoBlackouts
