# Typus Models Configuration File
#
# Use the README file as a reference to customize settings.

ScheduleMember:
  fields:
    default: effect_at, group_number, group_code, state
    form: group_number, group_code, state
    options:
      selectors: state, group_number, group_code
  relationships: schedule
  filters: schedule, group_number, group_code
  search: 
  application: TokyoBlackouts
  options:
    action_after_save: index

